<?php
/** Native complimentary ticket console; does not alter paid checkout or templates. */
if(!defined('ABSPATH'))exit;
if(!class_exists('MDG_Protocol_Tickets',false)){
final class MDG_Protocol_Tickets {
 const PAGE='mdg-protocol-tickets'; const INDEX='mdg_protocol_index_v1'; const PREFIX='mdg_protocol_batch_'; const MAX=100;
 static function hooks(){
  add_action('admin_menu',function(){add_submenu_page('mmc-dashboard','Protokol / Ücretsiz Biletler','Protokol / Ücretsiz Biletler','manage_woocommerce',self::PAGE,array(__CLASS__,'page'));},99);
  foreach(array('preview','issue','template','contacts','whatsapp','mark_sent') as $action)add_action('admin_post_mdg_protocol_'.$action,array(__CLASS__,$action));
  add_action('admin_notices',array(__CLASS__,'program_button'));
  add_action('template_redirect',array(__CLASS__,'public_page'),1);
  foreach(array('new_order','customer_processing_order','customer_completed_order','customer_on_hold_order') as $email)add_filter('woocommerce_email_enabled_'.$email,function($enabled,$order){return $order instanceof WC_Order&&$order->get_meta('_mdg_protocol_v1')?false:$enabled;},10,2);
  add_action('rest_api_init',function(){register_rest_route('mdg-protocol/v1','/diagnostics',array('methods'=>'GET','permission_callback'=>function(){return current_user_can('manage_woocommerce');},'callback'=>array(__CLASS__,'diagnostics')));});
 }
 static function guard(){if(!current_user_can('manage_woocommerce'))wp_die('Yetkisiz işlem.');}
 static function program_button(){
  if(!current_user_can('manage_woocommerce')||!isset($_GET['program_id'])||strpos((string)($_GET['page']??''),'mmc-')!==0)return;
  echo '<div class="notice notice-info"><p><a class="button" href="'.esc_url(add_query_arg(array('page'=>self::PAGE,'program_id'=>absint($_GET['program_id'])),admin_url('admin.php'))).'">Bu program için protokol / ücretsiz bilet</a></p></div>';
 }
 static function catalogue($program=0){
  global $wpdb;$out=array();$event_scope=0;
  if($program){$bridge=MMC_MDG_Bridge_Service::bridge_for_program($program);if(!$bridge||!$bridge->mdg_event_id)return array();$event_scope=(int)$bridge->mdg_event_id;}
  foreach((array)MDG_Public_Tickets::active_events() as $e){
   if($event_scope&&(int)$e->id!==$event_scope)continue;$sessions=array();
   $rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.MDG_DB::table('sessions').' WHERE event_id=%d AND status=%s AND start_at>%s ORDER BY start_at',(int)$e->id,'onsale',gmdate('Y-m-d H:i:s')));
   foreach($rows as $s){$types=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.MDG_DB::table('ticket_types').' WHERE session_id=%d AND is_active=1 AND capacity_units=1',(int)$s->id));
    foreach($types as $t){$role=strtoupper(remove_accents((string)$t->code));if(!in_array($role,array('YETISKIN','ADULT'),true))continue;$p=wc_get_product($t->wc_variation_id);
     if(!$p||!$p->is_type('variation')||$p->get_status()!=='publish'||(int)$p->get_parent_id()!==(int)$s->wc_product_id||(int)$p->get_meta('_mdg_session_id')!==(int)$s->id||get_post_meta($s->wc_product_id,'_tc_is_ticket',true)!=='yes')continue;
     $sessions[(int)$s->id]=array('id'=>(int)$s->id,'event'=>(int)$e->id,'time'=>wp_date('d.m.Y H:i',strtotime($s->start_at.' UTC'),new DateTimeZone('Europe/Istanbul')),'available'=>MDG_Capacity::available($s->id),'variation'=>(int)$t->wc_variation_id,'parent'=>(int)$s->wc_product_id,'type'=>(int)$t->id);break;
    }
   }
   if($sessions)$out[(int)$e->id]=array('event'=>$e,'sessions'=>$sessions);
  }return $out;
 }
 static function seat($raw){
  $s=strtoupper(remove_accents(trim((string)$raw)));$s=preg_replace('/\s+/u',' ',$s);
  if(preg_match('/^([A-Z]+)[ -]?0*([0-9]+)$/D',$s,$m))$s=$m[1].(int)$m[2];
  if($s!==''&&!preg_match('/^[A-Z0-9][A-Z0-9 ._-]{0,19}$/D',$s))throw new Exception('Koltuk numarası geçersiz: '.substr($s,0,20));return $s;
 }
 static function participants($mode,$count,$text,$section,$rows=null){
  if(!in_array($mode,array('named','seat','plain'),true))throw new Exception('Bilet biçimi geçersiz.');
  $out=array();$section=sanitize_text_field($section);
  if($mode==='plain'){if(!preg_match('/^[1-9][0-9]*$/D',(string)$count)||(int)$count>self::MAX)throw new Exception('Adet 1–100 arasında olmalı.');return array_fill(0,(int)$count,array('name'=>'','seat'=>'','section'=>''));}
  if($rows===null){$lines=preg_split('/\r\n|\r|\n/u',(string)$text);$rows=array();foreach($lines as $line){if(trim($line)==='')continue;$parts=explode('|',$line,2);$rows[]=$mode==='named'?array('name'=>trim($parts[0]),'phone'=>trim($parts[1]??''),'seat'=>'','section'=>$section):array('name'=>'','seat'=>$line,'section'=>$section);}}
  if(!$rows||count($rows)>self::MAX)throw new Exception('Liste 1–100 kişi içermeli.');$seen=array();
  foreach($rows as $i=>$r){$name=sanitize_text_field($r['name']??'');$seat=self::seat($r['seat']??'');$floor=sanitize_text_field($r['section']??$section);if(!$floor)$floor=$section;
   if($mode==='named'&&($name===''||strlen($name)>240))throw new Exception(($i+1).'. satırda ad soyad eksik veya çok uzun.');
   if($mode==='seat'&&$seat==='')throw new Exception(($i+1).'. satırda koltuk eksik.');
   if($seat!==''&&($floor===''||strlen($floor)>120))throw new Exception('Koltuklu biletler için bölüm/kat zorunlu.');
   $key=strtolower(remove_accents($floor)).'|'.$seat;if($seat!==''&&isset($seen[$key]))throw new Exception('Listede aynı koltuk iki kez var: '.$seat);$seen[$key]=true;
   $out[]=array('name'=>$name,'phone'=>self::phone($r['phone']??''),'seat'=>$seat,'section'=>$seat!==''?$floor:'');
  }return $out;
 }
 static function table_rows($table){
  if(!$table)throw new Exception('Dosya boş.');$header=array_map(function($x){return preg_replace('/[^a-z]/','',strtolower(remove_accents(preg_replace('/^\xEF\xBB\xBF/','',(string)$x))));},array_shift($table));
  $map=array();foreach($header as $i=>$h){if(in_array($h,array('adsoyad','isimsoyisim','fullname','name'),true))$map['name']=$i;if(in_array($h,array('bolum','kat','section'),true))$map['section']=$i;if(in_array($h,array('koltuk','koltukno','seat'),true))$map['seat']=$i;if(in_array($h,array('telefon','ceptelefonu','ceptelefon','gsm','phone','mobile'),true))$map['phone']=$i;}
  if(!isset($map['name']))throw new Exception('Excel/CSV ilk satırında ad_soyad sütunu bulunmalı.');$rows=array();
  foreach($table as $r){if(!array_filter($r,function($v){return trim((string)$v)!=='';}))continue;$row=array('name'=>'','phone'=>'','section'=>'','seat'=>'');foreach($map as $key=>$col)$row[$key]=(string)($r[$col]??'');$rows[]=$row;}return $rows;
 }
 static function xml($raw){if(!is_string($raw)||strlen($raw)>2097152||stripos($raw,'<!DOCTYPE')!==false||stripos($raw,'<!ENTITY')!==false)throw new Exception('Excel XML içeriği uygun değil.');$x=@simplexml_load_string($raw,'SimpleXMLElement',LIBXML_NONET);if(!$x)throw new Exception('Excel XML okunamadı.');return $x;}
 static function xlsx($path){
  if(!class_exists('ZipArchive')||!function_exists('simplexml_load_string'))throw new Exception('Excel okuma bileşeni bulunamadı.');$z=new ZipArchive();if($z->open($path)!==true)throw new Exception('Excel dosyası açılamadı.');
  try{
   $read=function($name)use($z){$stat=$z->statName($name);if(!$stat)return false;if($stat['size']>2097152)throw new Exception('Excel içeriği çok büyük.');return $z->getFromName($name);};
   $ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';$strings=array();$raw=$read('xl/sharedStrings.xml');if($raw!==false){$x=self::xml($raw);$x->registerXPathNamespace('m',$ns);foreach($x->xpath('//m:si') as $si){$si->registerXPathNamespace('m',$ns);$v='';foreach($si->xpath('.//m:t') as $t)$v.=(string)$t;$strings[]=$v;}}
   $w=self::xml($read('xl/workbook.xml'));$w->registerXPathNamespace('m',$ns);$sheets=$w->xpath('//m:sheets/m:sheet');if(!$sheets)throw new Exception('Excel sayfası yok.');$attrs=$sheets[0]->attributes('http://schemas.openxmlformats.org/officeDocument/2006/relationships');$rid=(string)$attrs['id'];
   $rels=self::xml($read('xl/_rels/workbook.xml.rels'));$rels->registerXPathNamespace('r','http://schemas.openxmlformats.org/package/2006/relationships');$target='';foreach($rels->xpath('//r:Relationship') as $rel){if((string)$rel['Id']===$rid)$target=ltrim((string)$rel['Target'],'/');}
   if(strpos($target,'xl/')!==0)$target='xl/'.$target;if(!preg_match('#^xl/worksheets/[A-Za-z0-9_-]+\.xml$#D',$target))throw new Exception('Excel sayfa bağlantısı geçersiz.');
   $x=self::xml($read($target));$x->registerXPathNamespace('m',$ns);$table=array();foreach($x->xpath('//m:sheetData/m:row') as $row){$row->registerXPathNamespace('m',$ns);$values=array();foreach($row->xpath('./m:c') as $cell){$cell->registerXPathNamespace('m',$ns);if($cell->xpath('./m:f'))throw new Exception('Liste formül değil, düz değer içermeli.');if(!preg_match('/^([A-Z]+)[0-9]+$/D',(string)$cell['r'],$m))throw new Exception('Excel hücresi geçersiz.');$col=0;foreach(str_split($m[1]) as $c)$col=$col*26+ord($c)-64;if($col>30)throw new Exception('Excel en fazla 30 sütun içermeli.');
    $type=(string)$cell['t'];$v=$cell->xpath('./m:v');$value=$v?(string)$v[0]:'';if($type==='s')$value=$strings[(int)$value]??'';elseif($type==='inlineStr'){$value='';foreach($cell->xpath('.//m:t') as $t)$value.=(string)$t;}$values[$col-1]=$value;
   }if($values){$dense=array_fill(0,max(array_keys($values))+1,'');foreach($values as $k=>$v)$dense[$k]=$v;$table[]=$dense;}if(count($table)>self::MAX+1)throw new Exception('Excel en fazla 100 kişi içermeli.');}return self::table_rows($table);
  }finally{$z->close();}
 }
 static function uploaded(){
  $f=$_FILES['list']??null;if(!$f||($f['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;
  if($f['error']!==UPLOAD_ERR_OK||$f['size']>4194304||!is_uploaded_file($f['tmp_name']))throw new Exception('Dosya yüklenemedi; sınır 4 MB.');$ext=strtolower(pathinfo($f['name'],PATHINFO_EXTENSION));
  if($ext==='xlsx')return self::xlsx($f['tmp_name']);if($ext!=='csv')throw new Exception('Excel .xlsx veya CSV yükleyin. Eski .xls dosyasını .xlsx olarak kaydedin.');
  $h=fopen($f['tmp_name'],'r');$first=fgets($h);rewind($h);$delimiter=substr_count($first,';')>substr_count($first,',')?';':',';$table=array();while(($r=fgetcsv($h,0,$delimiter))!==false){$table[]=$r;if(count($table)>self::MAX+1){fclose($h);throw new Exception('CSV en fazla 100 kişi içermeli.');}}fclose($h);return self::table_rows($table);
 }
 static function collision($sid,$people){
  $entries=get_posts(array('post_type'=>'tc_tickets_instances','post_status'=>'publish','numberposts'=>-1,'fields'=>'ids','meta_query'=>array(array('key'=>'_mdg_protocol_session','value'=>$sid),array('key'=>'_mdg_protocol_seat','compare'=>'EXISTS'))));$used=array();
  foreach($entries as $id){if(get_post_meta($id,'_mdg_invalidated',true))continue;$p=get_post($id);$o=$p?wc_get_order($p->post_parent):null;if(!$o||!in_array($o->get_status(),array('completed','processing','on-hold','pending'),true))continue;$used[strtolower(remove_accents((string)get_post_meta($id,'_mdg_protocol_section',true))).'|'.self::seat(get_post_meta($id,'_mdg_protocol_seat',true))]=true;}
  foreach($people as $p)if($p['seat']!==''&&isset($used[strtolower(remove_accents($p['section'])).'|'.$p['seat']]))throw new Exception('Bu seansa daha önce ayrılan koltuk: '.$p['section'].' '.$p['seat']);
 }
 static function load($id){if(!preg_match('/^[a-f0-9]{32}$/D',(string)$id))throw new Exception('Paket kimliği geçersiz.');$b=get_option(self::PREFIX.$id,array());if(!$b)throw new Exception('Paket bulunamadı.');return $b;}
 static function save($b){update_option(self::PREFIX.$b['id'],$b,false);$index=get_option(self::INDEX,array());if(!in_array($b['id'],$index,true)){$index[]=$b['id'];update_option(self::INDEX,$index,false);}}
 static function url($id){return add_query_arg(array('page'=>self::PAGE,'batch'=>$id),admin_url('admin.php'));}
 static function preview(){self::guard();check_admin_referer('mdg_protocol_preview');try{
  $mode=sanitize_key($_POST['mode']??'');$people=self::participants($mode,wp_unslash($_POST['count']??''),wp_unslash($_POST['people']??''),wp_unslash($_POST['section']??''),$mode==='named'?self::uploaded():null);
  $event=absint($_POST['event']??0);$cat=self::catalogue();if(!isset($cat[$event]))throw new Exception('Program satışa açık değil.');$sids=array_values(array_unique(array_map('absint',(array)($_POST['sessions']??array()))));if(!$sids||count($sids)>4)throw new Exception('1–4 seans seçin.');$sessions=array();foreach($sids as $sid){if(!isset($cat[$event]['sessions'][$sid]))throw new Exception('Seans bu programa ait değil.');$s=$cat[$event]['sessions'][$sid];if($s['available']<count($people))throw new Exception('Seans kapasitesi yetersiz.');self::collision($sid,$people);$sessions[$sid]=$s;}
  $kind=sanitize_key($_POST['kind']??'');if(!in_array($kind,array('protocol','free'),true))throw new Exception('Bilet kategorisi geçersiz.');$id=bin2hex(random_bytes(16));$b=array('id'=>$id,'created'=>time(),'user'=>get_current_user_id(),'title'=>sanitize_text_field(wp_unslash($_POST['title']??'')),'kind'=>$kind,'mode'=>$mode,'recipient_phone'=>self::phone(wp_unslash($_POST['recipient_phone']??'')),'event'=>$event,'event_name'=>$cat[$event]['event']->title,'venue'=>$cat[$event]['event']->venue_name,'sessions'=>$sessions,'people'=>$people,'orders'=>array(),'tickets'=>array(),'state'=>'preview');self::save($b);wp_safe_redirect(self::url($id));exit;
 }catch(Throwable $e){wp_die(esc_html($e->getMessage()),'Liste kontrolü',array('back_link'=>true));}}
 static function native_tickets($oid){return get_posts(array('post_type'=>'tc_tickets_instances','post_status'=>'publish','post_parent'=>$oid,'numberposts'=>self::MAX+1,'fields'=>'ids','orderby'=>'ID','order'=>'ASC'));}
 static function issue_batch($id){
  $b=self::load($id);if($b['user']!==get_current_user_id())throw new Exception('Bu önizleme başka kullanıcıya ait.');if($b['state']==='ready')return $b;if(time()-$b['created']>7200&&empty($b['orders']))throw new Exception('Önizleme süresi doldu; listeyi yeniden kontrol edin.');
  $locks=array();$sids=array_keys($b['sessions']);sort($sids,SORT_NUMERIC);
  try{
   foreach($sids as $sid){$key='mdg_protocol_session_lock_'.$sid;if(!add_option($key,time(),'','no'))throw new Exception('Bu seans için başka paket işleniyor.');$locks[]=$key;}
   $cat=self::catalogue();$n=count($b['people']);foreach($sids as $sid){if(!isset($cat[$b['event']]['sessions'][$sid]))throw new Exception('Seans artık satışta değil.');$current=$cat[$b['event']]['sessions'][$sid];if($current['variation']!==$b['sessions'][$sid]['variation'])throw new Exception('Ürün eşleştirmesi değişti.');if(empty($b['orders'][$sid])){if($current['available']<$n)throw new Exception('Seans kapasitesi yetersiz.');self::collision($sid,$b['people']);}}
   $b['state']='issuing';self::save($b);
   foreach($sids as $sid){$s=$b['sessions'][$sid];
    if(empty($b['orders'][$sid])){$o=wc_create_order(array('created_via'=>'mdg_protocol_console','status'=>'pending'));if(is_wp_error($o))throw new Exception($o->get_error_message());$o->update_meta_data('_mdg_protocol_v1',$id);$o->set_billing_first_name($b['kind']==='protocol'?'Protokol':'Ücretsiz');$o->set_billing_last_name('Bilet Paketi');$o->set_payment_method('mdg_protocol');$o->set_payment_method_title('Ücretsiz bilet');$o->save();$b['orders'][$sid]=$o->get_id();self::save($b);
     $item_id=$o->add_product(wc_get_product($s['variation']),$n,array('subtotal'=>0,'total'=>0));if(!$item_id)throw new Exception('Sipariş kalemi oluşturulamadı.');$item=$o->get_item($item_id);$item->set_name($b['kind']==='protocol'?'Protokol davetiyesi':'Ücretsiz bilet');$item->add_meta_data('mdg_session_id',$sid);$item->add_meta_data('_mdg_protocol_v1',$id);$item->save();$o->calculate_totals(false);$o->save();
    }else{$o=wc_get_order($b['orders'][$sid]);}
    if(!$o||$o->get_meta('_mdg_protocol_v1')!==$id||(float)$o->get_total()!==0.0||count($o->get_items())!==1)throw new Exception('Paket siparişi doğrulanamadı.');
    $items=$o->get_items();$item=reset($items);if((int)$item->get_quantity()!==$n||(int)$item->get_variation_id()!==$s['variation'])throw new Exception('Paket miktarı veya ürün değişmiş.');
    if($o->get_status()!=='completed'){if(!in_array($o->get_status(),array('pending','on-hold'),true))throw new Exception('Paket siparişi iptal/değişiklik durumunda.');MDG_Live_Sales::classic_order_processed($o->get_id(),array(),$o);$o->update_status('completed','Yetkili panelden ücretsiz bilet üretimi.');}
    $ids=self::native_tickets($o->get_id());if(count($ids)!==$n)throw new Exception('Native bilet sayısı beklenenle uyuşmuyor. Yeni sipariş üretilmedi; paketi tekrar kontrol edin.');
    $b['tickets'][$sid]=$ids;foreach($ids as $i=>$tid){if((int)get_post_meta($tid,'ticket_type_id',true)!==$s['variation']||!get_post_meta($tid,'ticket_code',true))throw new Exception('Native bilet kimliği uyuşmuyor.');$p=$b['people'][$i];update_post_meta($tid,'_mdg_protocol_v1',$id);update_post_meta($tid,'_mdg_protocol_session',$sid);update_post_meta($tid,'_mdg_protocol_seat',$p['seat']);update_post_meta($tid,'_mdg_protocol_section',$p['section']);update_post_meta($tid,'first_name',$p['name']!==''?$p['name']:($b['kind']==='protocol'?'Protokol misafiri':'Misafir'));update_post_meta($tid,'last_name',$p['seat']!==''?$p['section'].' '.$p['seat']:'');}self::save($b);
   }$b['state']='ready';$b['token']=bin2hex(random_bytes(24));self::save($b);$index=get_option(self::INDEX,array());if(!in_array($id,$index,true)){$index[]=$id;update_option(self::INDEX,$index,false);}return $b;
  }catch(Throwable $e){$b['state']='error';$b['error']=$e->getMessage();self::save($b);throw $e;}finally{foreach($locks as $key)delete_option($key);}
 }
 static function issue(){self::guard();$id=sanitize_key($_POST['batch']??'');check_admin_referer('mdg_protocol_issue_'.$id);try{self::issue_batch($id);}catch(Throwable $e){/* Persisted package error is shown without producing another order. */}wp_safe_redirect(self::url($id));exit;}
 static function xlsx_template($path){
  $z=new ZipArchive();if($z->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new Exception('Şablon oluşturulamadı.');$header='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
  $z->addFromString('[Content_Types].xml',$header.'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
  $z->addFromString('_rels/.rels',$header.'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  $z->addFromString('xl/workbook.xml',$header.'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Davetliler" sheetId="1" r:id="rId1"/></sheets></workbook>');
  $z->addFromString('xl/_rels/workbook.xml.rels',$header.'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');
  $body='';foreach(array(array('ad_soyad','bolum','koltuk','telefon'),array('Örnek İsim','','','')) as $i=>$row){$body.='<row r="'.($i+1).'">';foreach($row as $j=>$value)$body.='<c r="'.chr(65+$j).($i+1).'" t="inlineStr"><is><t>'.htmlspecialchars($value,ENT_XML1|ENT_QUOTES,'UTF-8').'</t></is></c>';$body.='</row>';}$z->addFromString('xl/worksheets/sheet1.xml',$header.'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'.$body.'</sheetData></worksheet>');$z->close();
 }
 static function template(){self::guard();check_admin_referer('mdg_protocol_template');$path=wp_tempnam('davetliler.xlsx');try{self::xlsx_template($path);nocache_headers();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="Protokol_Davetliler.xlsx"');readfile($path);}finally{@unlink($path);}exit;}
 static function package_url($b){return add_query_arg(array('mdg_protokol'=>$b['id'],'anahtar'=>$b['token']),home_url('/'));}

 static function phone($raw){
  $raw=trim((string)$raw);if($raw==='')return '';if(strlen($raw)>30||!preg_match('/^\+?[0-9 ()-]+$/D',$raw))throw new Exception('Cep telefonu geçersiz. 05xxxxxxxxx veya +ülke kodu kullanın.');$digits=preg_replace('/\D/','',$raw);
  if(preg_match('/^5[0-9]{9}$/D',$digits))return '90'.$digits;if(preg_match('/^05[0-9]{9}$/D',$digits))return '90'.substr($digits,1);if(preg_match('/^905[0-9]{9}$/D',$digits))return $digits;if($raw[0]==='+'&&preg_match('/^[1-9][0-9]{6,14}$/D',$digits))return $digits;throw new Exception('Cep telefonu geçersiz. Türkiye için 05xxxxxxxxx, diğer ülkeler için +ülke kodu kullanın.');
 }
 static function person_key($b,$i){return hash_hmac('sha256','protocol-person:'.(int)$i,$b['token']);}
 static function authorized_person($b,$key,$raw){
  if($raw===null){if(!hash_equals($b['token'],$key))throw new Exception('Paket geçersiz.');return null;}
  if(!is_scalar($raw)||!preg_match('/^(0|[1-9][0-9]*)$/D',(string)$raw)||!isset($b['people'][(int)$raw])||!hash_equals(self::person_key($b,(int)$raw),$key))throw new Exception('Kişisel bilet bağlantısı geçersiz.');return (int)$raw;
 }
 static function person_url($b,$i){return add_query_arg(array('mdg_protokol'=>$b['id'],'kisi'=>(int)$i,'anahtar'=>self::person_key($b,$i)),home_url('/'));}
 static function target($b,$raw){if($b['state']!=='ready')throw new Exception('Biletler henüz hazır değil.');if($raw==='all')return 'all';if(!is_string($raw)||!preg_match('/^(0|[1-9][0-9]*)$/D',$raw)||!isset($b['people'][(int)$raw]))throw new Exception('Alıcı geçersiz.');return (int)$raw;}
 static function target_phone($b,$target){return self::phone($target==='all'?($b['recipient_phone']??''):($b['people'][$target]['phone']??''));}
 static function whatsapp_url($b,$target){
  $phone=self::target_phone($b,$target);if(!$phone)throw new Exception('Önce alıcının cep telefonunu kaydedin.');$link=$target==='all'?self::package_url($b):self::person_url($b,$target);$times=array_column($b['sessions'],'time');$name=$target==='all'?'':($b['people'][$target]['name']??'');$text=($name!==''?'Merhaba '.$name.',\n':'').'🎪 Madagaskar Sirki '.($b['kind']==='protocol'?'protokol davetiyeniz':'ücretsiz biletiniz').' hazır.\n'.$b['event_name'].'\n📍 '.$b['venue'].'\n📅 '.implode(' / ',$times).'\n🎟️ Biletlerinizi açın: '.$link.'\nGirişte QR kodunuzu gösterin.';$text=str_replace('\n',"\n",$text);return 'https://wa.me/'.$phone.'?text='.rawurlencode($text);
 }
 static function contacts(){self::guard();$id=sanitize_key($_POST['batch']??'');check_admin_referer('mdg_protocol_contacts_'.$id);try{$b=self::load($id);if($b['state']!=='ready')throw new Exception('Biletler henüz hazır değil.');$all=self::phone(wp_unslash($_POST['recipient_phone']??''));$rows=(array)($_POST['phones']??array());$changes=array();foreach($b['people'] as $i=>$p)$changes[$i]=self::phone(wp_unslash($rows[$i]??''));if($all!==($b['recipient_phone']??''))unset($b['sharing']['all']);$b['recipient_phone']=$all;foreach($changes as $i=>$phone){if($phone!==($b['people'][$i]['phone']??''))unset($b['sharing'][$i]);$b['people'][$i]['phone']=$phone;}self::save($b);wp_safe_redirect(self::url($id));exit;}catch(Throwable $e){wp_die(esc_html($e->getMessage()),'Telefon kontrolü',array('back_link'=>true));}}
 static function whatsapp(){self::guard();$id=sanitize_key($_POST['batch']??'');check_admin_referer('mdg_protocol_whatsapp_'.$id);try{$b=self::load($id);$target=self::target($b,$_POST['target']??'');$url=self::whatsapp_url($b,$target);$b['sharing'][$target]=array('state'=>'opened','at'=>time(),'user'=>get_current_user_id());self::save($b);nocache_headers();header('Referrer-Policy: no-referrer');wp_redirect($url,303);exit;}catch(Throwable $e){wp_die(esc_html($e->getMessage()),'WhatsApp paylaşımı',array('back_link'=>true));}}
 static function mark_sent(){self::guard();$id=sanitize_key($_POST['batch']??'');check_admin_referer('mdg_protocol_mark_sent_'.$id);try{$b=self::load($id);$target=self::target($b,$_POST['target']??'');if(!self::target_phone($b,$target))throw new Exception('Alıcının telefonu eksik.');$b['sharing'][$target]=array('state'=>'manual_sent','at'=>time(),'user'=>get_current_user_id());self::save($b);wp_safe_redirect(self::url($id));exit;}catch(Throwable $e){wp_die(esc_html($e->getMessage()),'Paylaşım kaydı',array('back_link'=>true));}}
 static function share_controls($b,$target){
  $phone=self::target_phone($b,$target);$state=$b['sharing'][$target]??array();$label=array('opened'=>'WhatsApp açıldı; gönderim onayı bekleniyor','manual_sent'=>'Gönderdim — yönetici beyanı')[$state['state']??'']??'Henüz paylaşılmadı';echo '<span>'.esc_html($label).'</span>';if(!empty($state['at']))echo ' <small>'.esc_html(wp_date('d.m.Y H:i',$state['at'],new DateTimeZone('Europe/Istanbul'))).'</small>';if(!$phone){echo '<p>Telefonu kaydedin.</p>';return;}
  foreach(array('whatsapp'=>'WhatsApp’ta aç','mark_sent'=>'Gönderdim olarak işaretle') as $action=>$label){echo '<form method="post" '.($action==='whatsapp'?'target="_blank" ':'').'action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline-block;margin:5px"><input type="hidden" name="action" value="mdg_protocol_'.$action.'"><input type="hidden" name="batch" value="'.esc_attr($b['id']).'"><input type="hidden" name="target" value="'.esc_attr($target).'">';wp_nonce_field('mdg_protocol_'.$action.'_'.$b['id']);echo '<button class="button">'.esc_html($label).'</button></form>';}
 }
 static function sharing_view($b){
  echo '<h2>WhatsApp ile paylaş</h2><p>Telefonları kaydedin, ardından WhatsApp’ta aç butonuna basıp mesajı WhatsApp içinden gönderin. Sistem teslimat teyidi almaz. Gönderdim işareti sizin beyanınızı kaydeder. Kişi bağlantısı yalnız o kişinin tüm seçili seanslardaki biletlerini açar; paket alıcısı tüm biletlere erişir.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="mdg_protocol_contacts"><input type="hidden" name="batch" value="'.esc_attr($b['id']).'">';wp_nonce_field('mdg_protocol_contacts_'.$b['id']);echo '<p><label>Paket alıcısının cep telefonu <input type="tel" name="recipient_phone" maxlength="25" value="'.esc_attr($b['recipient_phone']??'').'" placeholder="05xxxxxxxxx"></label></p><table class="widefat"><tr><th>Kişi</th><th>Cep telefonu</th></tr>';foreach($b['people'] as $i=>$p)echo '<tr><td>'.esc_html($p['name']?:('Misafir '.($i+1))).'</td><td><input type="tel" name="phones['.$i.']" maxlength="25" value="'.esc_attr($p['phone']??'').'" placeholder="05xxxxxxxxx"></td></tr>';echo '</table><p><button class="button button-primary">Telefonları kaydet</button></p></form><h3>Paket alıcısı — tüm biletler</h3>';self::share_controls($b,'all');echo '<h3>Kişilere ayrı paylaşım</h3><table class="widefat"><tr><th>Kişi</th><th>Paylaşım</th></tr>';foreach($b['people'] as $i=>$p){echo '<tr><td>'.esc_html($p['name']?:('Misafir '.($i+1))).'</td><td>';self::share_controls($b,$i);echo '</td></tr>';}echo '</table>';
 }
 static function page(){self::guard();echo '<div class="wrap"><h1>Protokol / Ücretsiz Biletler</h1><p>İsimli, koltuklu veya numarasız ücretsiz bilet hazırlayın. Önizleme sonrası her kişi ve seans için ayrı giriş QR kodu üretilir.</p>';
  try{if(isset($_GET['batch'])){self::batch_view(self::load(sanitize_key($_GET['batch'])));echo '</div>';return;}}catch(Throwable $e){echo '<div class="notice notice-error"><p>'.esc_html($e->getMessage()).'</p></div>';}
  $program=absint($_GET['program_id']??0);$cat=self::catalogue($program);$eid=absint($_GET['event']??0);if(!$eid&&count($cat)===1)$eid=(int)array_key_first($cat);
  echo '<form method="get"><input type="hidden" name="page" value="'.self::PAGE.'"><input type="hidden" name="program_id" value="'.$program.'"><label>Program / etkinlik <select name="event" required><option value="">Seçin</option>';foreach($cat as $id=>$r)echo '<option value="'.$id.'" '.selected($id,$eid,false).'>'.esc_html($r['event']->title).'</option>';echo '</select></label> <button class="button">Seansları göster</button></form>';
  if(isset($cat[$eid])){echo '<form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'" style="max-width:900px"><input type="hidden" name="action" value="mdg_protocol_preview"><input type="hidden" name="event" value="'.$eid.'">';wp_nonce_field('mdg_protocol_preview');echo '<h2>1. Seanslar</h2>';foreach($cat[$eid]['sessions'] as $sid=>$s)echo '<p><label><input type="checkbox" name="sessions[]" value="'.$sid.'"> '.esc_html($s['time']).' — Kalan kapasite: '.(int)$s['available'].'</label></p>';
   echo '<h2>2. Bilet biçimi</h2><p><label>Kategori <select name="kind"><option value="protocol">Protokol davetiyesi</option><option value="free">Ücretsiz bilet</option></select></label></p><p><label>Kurum / paket adı <input name="title" maxlength="120" placeholder="Örn. Denizli protokol"></label></p><p><label>Üretim biçimi <select name="mode" id="mdg-protocol-mode"><option value="named">İsimli liste (Excel veya elle)</option><option value="seat">Koltuk numaralı liste</option><option value="plain">Numarasız, adetle</option></select></label></p>';
   echo '<div data-modes="named seat"><p><label>Bölüm / kat <input name="section" maxlength="80" placeholder="Ana salon / Balkon"></label><br><small>Koltuk yazılacaksa zorunlu. Excelde bölüm varsa satırdaki değer kullanılır.</small></p></div><div data-modes="named"><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=mdg_protocol_template'),'mdg_protocol_template')).'">Excel şablonunu indir</a></p><p><label>Excel (.xlsx) veya CSV listesi <input type="file" name="list" accept=".xlsx,.csv"></label><br><small>İlk sayfa: ad_soyad, bolum, koltuk, telefon sütunları. Telefonu metin olarak yazın (05… veya +ülke kodu). Örnek İsim satırını kendi listenizle değiştirin. Koltuk ve bölüm isteğe bağlıdır. Dosya yüklenirse elle girilen liste yerine dosya kullanılır.</small></p></div><div data-modes="named seat"><p><label id="mdg-protocol-list-label">Her satıra bir ad soyad veya koltuk numarası</label><br><textarea name="people" rows="8" cols="60" placeholder="İsimli: Ad Soyad | 05xxxxxxxxx (telefon isteğe bağlı). Koltuklu: A2, A3 ... her biri ayrı satır."></textarea></p></div><div data-modes="plain"><p><label>Bilet adedi <input name="count" type="number" min="1" max="100" value="10"></label></p></div><p><label>Paket alıcısının cep telefonu (isteğe bağlı) <input type="tel" name="recipient_phone" maxlength="25" placeholder="05xxxxxxxxx"></label><br><small>Bu numaraya tüm paket paylaşılır. Kişi telefonları yalnız kendi biletlerini açar.</small></p><p>Liste en fazla 100 kişi, bir paket en fazla 4 seans içerebilir. Seçtiğiniz her seansa aynı liste uygulanır. Koltuklar salonda ayrıca rezerve edilmelidir.</p><button class="button button-primary">Listeyi kontrol et ve önizle</button></form><script>(function(){const s=document.getElementById("mdg-protocol-mode");const update=()=>document.querySelectorAll("[data-modes]").forEach(x=>{x.hidden=!x.dataset.modes.split(" ").includes(s.value);});s.addEventListener("change",update);update();})();</script>';
  }elseif(!$cat)echo '<p>Bu kapsamda satışa açık ve bilet eşleştirmesi tamamlanmış program bulunamadı.</p>';
  echo '<h2>Oluşturulan paketler</h2><table class="widefat"><tr><th>Paket</th><th>Program</th><th>Adet</th><th>İşlem</th></tr>';foreach(array_slice(array_reverse(get_option(self::INDEX,array())),0,100) as $id){$b=get_option(self::PREFIX.$id,array());if(!$b)continue;echo '<tr><td>'.esc_html($b['title']?:($b['kind']==='protocol'?'Protokol davetiyesi':'Ücretsiz bilet')).'</td><td>'.esc_html($b['event_name']).'</td><td>'.count($b['people']).' × '.count($b['sessions']).' seans · '.esc_html(array('preview'=>'Önizleme','issuing'=>'İşleniyor','error'=>'Kontrol gerekli','ready'=>'Hazır')[$b['state']]??$b['state']).'</td><td><a href="'.esc_url(self::url($id)).'">Paketi aç</a></td></tr>';}echo '</table>';
  if(class_exists('MDG_Denizli_Invitations')){$s=MDG_Denizli_Invitations::status();if($s['ready'])echo '<p><a class="button" href="'.esc_url($s['url']).'">Mevcut Denizli A2–A11 protokol paketi — 20 bilet</a></p>';}echo '</div>';
 }
 static function batch_view($b){
  echo '<h2>'.esc_html($b['title']?:'Bilet paketi').'</h2><p>'.esc_html($b['event_name'].' — '.$b['venue']).'</p><p>'.count($b['people']).' kişi × '.count($b['sessions']).' seans = <strong>'.(count($b['people'])*count($b['sessions'])).' bilet · Toplam 0 TL</strong></p>';foreach($b['sessions'] as $s)echo '<p>Seans: '.esc_html($s['time']).'</p>';
  if($b['state']==='ready'){echo '<p><a class="button button-primary" href="'.esc_url(self::package_url($b)).'" target="_blank" rel="noopener">Online bilet paketini aç</a></p><p>Bu paket bağlantısını davetlilerle paylaşabilirsiniz. Biletler tek tek PDF olarak açılır.</p>';}elseif($b['user']===get_current_user_id()){
   if(!empty($b['error']))echo '<div class="notice notice-error"><p>'.esc_html($b['error']).'</p><p>Mevcut siparişler korunur; tekrar deneme aynı paket üzerinden devam eder.</p></div>';
   echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="mdg_protocol_issue"><input type="hidden" name="batch" value="'.esc_attr($b['id']).'">';wp_nonce_field('mdg_protocol_issue_'.$b['id']);echo '<button class="button button-primary">'.($b['state']==='error'?'Mevcut paketi tekrar kontrol et':'Ücretsiz QR biletlerini üret').'</button></form>';
  }
  if($b['state']==='ready')self::sharing_view($b);
  echo '<table class="widefat" style="margin-top:20px"><tr><th>#</th><th>Ad soyad</th><th>Telefon</th><th>Bölüm</th><th>Koltuk</th></tr>';foreach($b['people'] as $i=>$p)echo '<tr><td>'.($i+1).'</td><td>'.esc_html($p['name']?:'Misafir').'</td><td>'.esc_html($p['phone']??'').'</td><td>'.esc_html($p['section']?:'—').'</td><td>'.esc_html($p['seat']?:'Numarasız').'</td></tr>';echo '</table><p><a href="'.esc_url(admin_url('admin.php?page='.self::PAGE)).'">Yeni paket / tüm paketler</a></p>';
 }
 static function ticket_data($tid,$b,$person){$f=MDG_Ticket_Session_Datetime::designer_class('TC_Ticket_Designer_Fields');$data=$f::resolve_ticket_data($tid);$data=MDG_Ticket_Session_Datetime::correct_ticket_data($data,$tid);$label=$person['name']?:'Misafir';$label.=$person['seat']!==''?' · '.$person['section'].' · '.$person['seat']:' · Numarasız / serbest oturma';$data['attendee_name']=$label;$data['el_tc_ticket_type_element_custom']=$b['kind']==='protocol'?'PROTOKOL DAVETİYESİ':'ÜCRETSİZ BİLET';return $data;}
 static function public_page(){if(!isset($_GET['mdg_protokol']))return;nocache_headers();header('X-Robots-Tag: noindex, nofollow');header('Referrer-Policy: no-referrer');try{$b=self::load(sanitize_key($_GET['mdg_protokol']));$key=is_string($_GET['anahtar']??null)?$_GET['anahtar']:'';if($b['state']!=='ready')throw new Exception('Paket geçersiz.');$person=self::authorized_person($b,$key,$_GET['kisi']??null);$all=array();foreach($b['orders'] as $sid=>$oid){$o=wc_get_order($oid);if(!$o||$o->get_status()!=='completed')continue;foreach($b['tickets'][$sid] as $i=>$tid)if(($person===null||$person===$i)&&get_post_status($tid)==='publish'&&!get_post_meta($tid,'_mdg_invalidated',true))$all[$tid]=array('session'=>$sid,'person'=>$b['people'][$i]);}
   if(isset($_GET['bilet'])){$tid=absint($_GET['bilet']);if(!isset($all[$tid]))throw new Exception('Bilet geçersiz.');$f=MDG_Ticket_Session_Datetime::designer_class('TC_Ticket_Designer_Template');$g=MDG_Ticket_Session_Datetime::designer_class('TC_Ticket_Designer_PDF_Generator');$type=(int)get_post_meta($tid,'ticket_type_id',true);$template=(int)get_post_meta($type,'tc_designer_template_id',true);if(!$template)throw new Exception('PDF şablonu bulunamadı.');if(function_exists('tickera_ticket_designer_ensure_tcpdf'))tickera_ticket_designer_ensure_tcpdf();$pdf=class_exists('MDG_Protocol_PDF')?MDG_Protocol_PDF::render($template,self::ticket_data($tid,$b,$all[$tid]['person'])):$g::generate(new $f($template),self::ticket_data($tid,$b,$all[$tid]['person']),'S','bilet.pdf');if(!is_string($pdf)||substr($pdf,0,5)!=='%PDF-')throw new Exception('PDF oluşturulamadı.');header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="Davetiye-'.$tid.'.pdf"');echo $pdf;exit;}
   echo '<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Bilet paketi</title><style>body{font:18px system-ui;max-width:900px;margin:30px auto;padding:18px;background:#fff9ed}a{display:block;padding:12px;margin:8px;background:#a63225;color:white;border-radius:7px}</style></head><body><h1>'.esc_html($b['title']?:($b['kind']==='protocol'?'Protokol davetiyeleri':'Ücretsiz biletler')).'</h1><p>'.esc_html($b['event_name'].' · '.$b['venue']).'</p>';foreach($b['sessions'] as $sid=>$s){echo '<h2>'.esc_html($s['time']).'</h2>';foreach($all as $tid=>$r){if($r['session']!=$sid)continue;$p=$r['person'];$label=$p['name']?:'Misafir';$label.=$p['seat']!==''?' · '.$p['section'].' '.$p['seat']:' · Numarasız';echo '<a href="'.esc_url(add_query_arg('bilet',$tid,$person===null?self::package_url($b):self::person_url($b,$person))).'">'.esc_html($label).' — PDF aç</a>';}}echo '<p>Her bilet bir kişilik ve yalnız üzerindeki seans için geçerlidir. Giriş QR kodunu salon girişinde okutun.</p></body></html>';exit;
  }catch(Throwable $e){status_header(404);echo esc_html($e->getMessage());exit;}}
 static function diagnostics(){
  $cat=self::catalogue();$checks=array();$checks['excel_supported']=class_exists('ZipArchive')&&function_exists('simplexml_load_string');if($checks['excel_supported']){$file=wp_tempnam('protocol-test.xlsx');try{self::xlsx_template($file);$rows=self::xlsx($file);$checks['excel_roundtrip']=count($rows)===1&&$rows[0]['name']==='Örnek İsim';$z=new ZipArchive();$z->open($file);$ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';$z->addFromString('xl/sharedStrings.xml','<sst xmlns="'.$ns.'"><si><t>ad_soyad</t></si><si><t>bolum</t></si><si><t>koltuk</t></si><si><t>Excel Kontrolü</t></si><si><t>Ana salon</t></si><si><t>B2</t></si></sst>');$z->addFromString('xl/worksheets/sheet1.xml','<worksheet xmlns="'.$ns.'"><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c></row><row r="2"><c r="A2" t="s"><v>3</v></c><c r="B2" t="s"><v>4</v></c><c r="C2" t="s"><v>5</v></c></row></sheetData></worksheet>');$z->close();$rows=self::xlsx($file);$people=self::participants('named','','','',$rows);$checks['excel_shared_strings']=count($people)===1&&$people[0]['name']==='Excel Kontrolü'&&$people[0]['seat']==='B2'&&$people[0]['section']==='Ana salon';}finally{@unlink($file);}}
  try{self::collision(99,array(array('name'=>'','seat'=>'A2','section'=>'Ana salon')));$checks['legacy_seat_collision']=false;}catch(Throwable $e){$checks['legacy_seat_collision']=true;}
  $checks['input_modes']=count(self::participants('plain','10','',''))===10&&count(self::participants('named','',"İsim Kontrolü\nİkinci Kontrol",''))===2&&count(self::participants('seat','',"B2\nB3",'Ana salon'))===2;$checks['page_slug']=self::PAGE;$checks['catalogue_events']=count($cat);$checks['denizli_sessions']=array_keys($cat[12]['sessions']??array());$checks['phone_normalization']=self::phone('0532 000 00 00')==='905320000000';$fixture=array('id'=>str_repeat('a',32),'token'=>str_repeat('b',48),'people'=>array(array('name'=>'Kontrol','phone'=>'905320000000')));$checks['existing_kommo_link_bridge']=function_exists('ms_kommo_schedule_bilet_sync');$checks['person_scope']=self::authorized_person($fixture,self::person_key($fixture,0),'0')===0;try{self::authorized_person($fixture,self::person_key($fixture,0),'1');$checks['person_scope']=false;}catch(Throwable $e){}$fixture+=array('state'=>'ready','kind'=>'protocol','event_name'=>'Kontrol','venue'=>'Kontrol salonu','sessions'=>array(array('time'=>'08.10.2026 17:30')),'recipient_phone'=>'905320000001');ob_start();self::sharing_view($fixture);$sharing=ob_get_clean();$checks['sharing_rendered']=strpos($sharing,'Telefonları kaydet')!==false&&strpos($sharing,'mdg_protocol_whatsapp')!==false&&strpos($sharing,'mdg_protocol_mark_sent')!==false;$checks['manual_delivery_labels']=strpos($sharing,'Sistem teslimat teyidi almaz.')!==false;try{self::whatsapp_url($fixture,0);$checks['whatsapp_link']=true;}catch(Throwable $e){$checks['whatsapp_link']=false;}$checks['no_generation']=true;$checks['history_count']=count(get_option(self::INDEX,array()));ob_start();$old=$_GET;$_GET=array('event'=>12);self::page();$_GET=$old;$html=ob_get_clean();$checks['admin_rendered']=strpos($html,'Excel şablonunu indir')!==false&&strpos($html,'Listeyi kontrol et ve önizle')!==false;$checks['admin_html']=$html;return $checks;
 }
}
MDG_Protocol_Tickets::hooks();

}
