<?php
/** Real adoption transaction/CAS/duplicate/backfill regression. Ephemeral CI DB only. */
require __DIR__.'/automation-v2-mysql.php';
$db->query("ALTER TABLE wp_mmc_programs ADD program_code varchar(100),ADD province_name varchar(100),ADD district_name varchar(100)");
function reset_legacy($fields=[]){global$db;reset_task();$db->query("UPDATE wp_mmc_operation_plans SET departure_at='2026-10-08 09:00:00'");$title=MMC_Operations_Service::task_templates()['plan'][1];$sql=$db->prepare('UPDATE wp_mmc_tasks SET title=%s,metadata=NULL,notes=%s,due_at=NULL,assigned_user_id=NULL WHERE id=1',$title,'');$db->query($sql);foreach($fields as$k=>$v){$db->query($db->prepare("UPDATE wp_mmc_tasks SET $k=%s WHERE id=1",$v));}}
function task_snapshot(){global$db;return json_encode($db->get_results('SELECT * FROM wp_mmc_tasks ORDER BY id',ARRAY_A));}
reset_legacy();$before=task_snapshot();$p=MMC_Operations_Service::task_adoption_preview(77);test($p['would_adopt']===1&&$p['would_update_due']===1&&$p['would_update_owner']===1,'Real adoption preview');test(task_snapshot()===$before,'Real GET mutated');
$r=MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']);test(!is_wp_error($r)&&$r['adopted']===1,'Real adoption SQL');
$after=$db->get_row('SELECT * FROM wp_mmc_tasks');$old=json_decode($before,true)[0];$diff=[];foreach((array)$after as$k=>$v){if($old[$k]!==$v)$diff[]=$k;}test($diff===['metadata'],'Adoption changed columns beyond metadata');
test($after->due_at===null&&$after->assigned_user_id===null,'Adoption applied backfill');test((int)$db->get_var('SELECT COUNT(*) FROM wp_mmc_logs')===0,'Adoption emitted domain log');
$r=MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']);test($r['adopted']===0,'Double adoption not idempotent');
$p=MMC_Operations_Service::task_automation_preview(77);test($p['would_update_due']===1&&$p['would_update_owner']===1,'Adopted task not managed');
$r=MMC_Operations_Service::apply_task_automation(77);test($r['tasks_updated']===1,'Separate explicit backfill');$after=$db->get_row('SELECT * FROM wp_mmc_tasks');test($after->due_at==='2026-10-08 09:00:00'&&(int)$after->assigned_user_id===501,'Backfill values');
test(MMC_Operations_Service::task_alerts(0,'mine')['counts']['mine']===1,'My tasks after apply');
$db->query("UPDATE wp_mmc_tasks SET due_at='2026-10-07 11:00:00',assigned_user_id=502");test(MMC_Operations_Service::apply_task_automation(77)['tasks_updated']===0,'Manual override lost');
reset_legacy(['due_at'=>'2026-10-07 11:00:00','assigned_user_id'=>502]);$p=MMC_Operations_Service::task_adoption_preview(77);$r=MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']);test($r['adopted']===1,'Task with manual values adoption');test(MMC_Operations_Service::apply_task_automation(77)['tasks_updated']===0,'Manual fields overwritten after adoption');
reset_legacy(['metadata'=>json_encode(['source_key'=>'operations_v1.plan','template_version'=>1,'system_generated'=>false,'phase'=>'pre_departure'])]);$p=MMC_Operations_Service::task_adoption_preview(77);$r=MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']);$m=json_decode($db->get_var('SELECT metadata FROM wp_mmc_tasks'),true);test($r['adopted']===1&&$m['phase']==='pre_departure'&&$m['template_version']===1,'Metadata merge');
reset_legacy();$db->query('INSERT INTO wp_mmc_tasks SELECT 2,program_id,module,title,status,priority,due_at,assigned_user_id,completed_at,metadata,notes,updated_at FROM wp_mmc_tasks WHERE id=1');$p=MMC_Operations_Service::task_adoption_preview(77);$before=task_snapshot();test($p['counts']['DUPLICATE']===2,'Duplicate inventory');test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'Duplicate mutated');
reset_legacy();$p=MMC_Operations_Service::task_adoption_preview(77);$db->query("UPDATE wp_mmc_tasks SET notes='manual' WHERE id=1");$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'Stale snapshot accepted');
reset_legacy();$p=MMC_Operations_Service::task_adoption_preview(77);$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[999],$p['snapshot']))&&task_snapshot()===$before,'Cross program/missing selection');
reset_legacy();$db->query("UPDATE wp_mmc_programs SET status='cancelled' WHERE id=77");$p=MMC_Operations_Service::task_adoption_preview(77);$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'Cancelled adoption');
reset_legacy();$db->query("UPDATE wp_mmc_tasks SET status='completed' WHERE id=1");$p=MMC_Operations_Service::task_adoption_preview(77);$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'Closed task adoption');
reset_legacy();$p=MMC_Operations_Service::task_adoption_preview(77);$db->manual_race=true;$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'CAS failed to rollback transaction');
reset_legacy();$p=MMC_Operations_Service::task_adoption_preview(77);$db->cancel_race=true;$before=task_snapshot();test(is_wp_error(MMC_Operations_Service::adopt_legacy_tasks(77,[1],$p['snapshot']))&&task_snapshot()===$before,'Cancellation race accepted');
echo "PASS {$assertions} real MySQL assertions; adoption metadata-only/transaction/CAS/idempotency and separate backfill.\n";
